// gen-tokens.mjs — the ONE source→TS bridge for @hanzo/design.
// The hand-authored token CSS under tokens/*.css is the source of truth; this
// script parses every `--name: value;` custom property out of it and emits a
// typed TypeScript module (src/tokens.gen.ts). CSS and code therefore can never
// drift — you edit a token in ONE place (the CSS) and both the stylesheet and
// the programmatic API update. Run via `npm run gen` (part of `build`).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = join(root, 'tokens')

// The token files, in the same order styles.css imports them. base.css is the
// semantic-alias layer (references other vars) — parsed too, so `--background`
// etc. are available programmatically.
const FILES = ['colors', 'typography', 'spacing', 'grid', 'radius', 'elevation', 'motion', 'z', 'fonts', 'base']

// group name for each file (the export const); a couple read better renamed.
const GROUP = { z: 'zIndex' }

/** Strip /* *​/ comments, then pull every `--name: value;` pair (multi-per-line ok). */
function parse(css) {
  const noComments = css.replace(/\/\*[\s\S]*?\*\//g, '')
  const out = []
  const re = /--([A-Za-z0-9-]+)\s*:\s*([^;]+);/g
  let m
  while ((m = re.exec(noComments))) out.push([m[1].trim(), m[2].trim()])
  return out
}

// A token may be authored more than once — the dark `:root{}` default and a
// light `@media`/`[data-theme]` override carry the SAME name. Keep the FIRST
// occurrence (dark, the default theme): the static map is the authored default;
// live theme switching happens through the CSS cascade via cssVar()/var(--x).
const groupMaps = {} // groupName -> Map(name->value), first-wins
const flatMap = new Map() // '--name' -> value, first-wins
for (const f of FILES) {
  let css
  try {
    css = readFileSync(join(tokensDir, `${f}.css`), 'utf8')
  } catch {
    continue
  }
  const g = GROUP[f] ?? f
  const gm = (groupMaps[g] ??= new Map())
  for (const [n, v] of parse(css)) {
    if (!gm.has(n)) gm.set(n, v)
    if (!flatMap.has(`--${n}`)) flatMap.set(`--${n}`, v)
  }
}
const groups = Object.fromEntries(Object.entries(groupMaps).map(([g, m]) => [g, [...m]]))
const flat = [...flatMap]

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
const objLit = (pairs) =>
  '{\n' + pairs.map(([n, v]) => `  '${esc(n)}': '${esc(v)}',`).join('\n') + '\n} as const'

let ts = `// AUTO-GENERATED by scripts/gen-tokens.mjs from tokens/*.css — DO NOT EDIT.
// Edit the token in tokens/<group>.css and re-run \`npm run gen\`.
/* eslint-disable */

`

// Per-group typed maps (keyed by the var name WITHOUT the leading '--').
for (const [g, pairs] of Object.entries(groups)) {
  ts += `/** ${g} tokens (from tokens/${Object.keys(GROUP).find((k) => GROUP[k] === g) ?? g}.css). Values are raw CSS. */\n`
  ts += `export const ${g} = ${objLit(pairs)}\n\n`
}

// The complete flat map, keyed by the literal CSS custom-property name.
ts += `/** Every token, keyed by its literal CSS custom-property name ('--background', …). */\n`
ts += `export const cssVars = ${objLit(flat)}\n\n`

ts += `export type CssVarName = keyof typeof cssVars\n`

writeFileSync(join(root, 'src', 'tokens.gen.ts'), ts)
console.log(`gen-tokens: wrote src/tokens.gen.ts — ${flat.length} tokens across ${Object.keys(groups).length} groups`)

// ── styles.css, FLATTENED ────────────────────────────────────────────────
// The entry point says "import THIS one file", and for a long time no bundler
// could. It was a list of `@import url("tokens/*.css")`, and a relative url
// resolves against the file doing the importing — so a consumer's
// `@import "@hanzo/design/styles.css"` sent webpack looking for
// `<their app>/tokens/fonts.css` and the build died on a module it never had.
// Nested imports also have to precede every other rule, which the spec then
// invalidates the moment the consumer imports anything before them; browsers
// drop them silently, every token resolves to nothing, and `border-border`
// falls back to currentColor — a stark white hairline on black.
//
// Both failures are the same fact: an @import list is not a stylesheet a
// consumer can use. So the entry point is now the CONTENT, concatenated in the
// same order, with no imports to resolve and no order to get wrong. That is why
// nothing consumed this package and every app hand-rolled its own palette.
//
// Authoring does not change: tokens/*.css stays the source of truth and this is
// its build product, exactly like tokens.gen.ts.
const banner = `/* Hanzo Design System — the entry point. Import THIS one file.
 *
 * AUTO-GENERATED by scripts/gen-tokens.mjs from tokens/*.css — DO NOT EDIT.
 * Edit the token in tokens/<group>.css and re-run "npm run gen".
 *
 * Flattened deliberately: a consumer's bundler resolves a nested url() against
 * ITS OWN directory, not ours, so an @import list here is a build error in
 * every app that follows the instruction above. Nested imports must also
 * precede all other rules, which the spec invalidates the moment the consumer
 * imports anything first — browsers then drop them silently and every token
 * resolves to nothing. The content is inlined in the order the groups were
 * always imported in.
 */
`
// Hoisting a file from tokens/ to the package root moves what its relative
// url()s point at. tokens/fonts.css says `../assets/fonts/Geist-Variable.woff2`
// — correct from tokens/, one directory too high from the root, where it lands
// outside the package entirely and every consumer's build fails on a missing
// module. Rebasing is therefore part of flattening, not an afterthought: the
// bundle is one level shallower, so `../` becomes `./`.
const rebase = (css) =>
  css.replace(/url\((\s*['"]?)\.\.\/(?!\.)/g, 'url($1./')

const bundle = banner + FILES.map((f) => {
  const css = rebase(readFileSync(join(tokensDir, `${f}.css`), 'utf8').trim())
  return `\n/* ── tokens/${f}.css ─────────────────────────────────────── */\n${css}\n`
}).join('')
writeFileSync(join(root, 'styles.css'), bundle)
console.log(`gen-tokens: wrote styles.css — ${FILES.length} token groups, flattened`)

// ── tailwind.css — the ONE line a Tailwind app writes ────────────────────
// Every app that consumed these tokens still had to hand-write the bridge from
// our variable names to Tailwind's utility namespace:
//
//   @theme inline { --color-background: var(--background); ...twenty more }
//
// Twenty lines of boilerplate, copied into each new app, is a drift vector with
// a silent failure mode: miss one and that utility resolves to nothing —
// `border-border` becomes currentColor and paints a white hairline on black,
// which reads as a design choice rather than a missing line. Tabs shipped with
// three of these and used forty-one.
//
// So the bridge is generated here from SLOTS, and an app writes one import
// after `@import "tailwindcss"`. There is nothing left to get wrong, and adding
// a semantic token wires it up for every app at once.
const SLOTS = [
  'background', 'foreground',
  'card', 'card-foreground',
  'popover', 'popover-foreground',
  'primary', 'primary-foreground',
  'secondary', 'secondary-foreground',
  'muted', 'muted-foreground',
  'accent', 'accent-foreground',
  'destructive', 'destructive-foreground',
  'border', 'input', 'ring',
]
// State colours are their own vocabulary and keep their names, so `text-error`
// and `bg-online` mean what they say instead of borrowing a neutral slot.
const STATE = { error: 'state-error', success: 'state-success', online: 'state-online' }

const declared = new Set(flat.map(([n]) => n.replace(/^--/, '')))
const missing = SLOTS.filter((s) => !declared.has(s))
if (missing.length) {
  console.error(`gen-tokens: tokens/colors.css declares no --${missing.join(', --')}`)
  process.exit(1)
}

const tw = `/* Hanzo Design System — Tailwind v4 bridge. The ONE import a Tailwind app adds.
 *
 * AUTO-GENERATED by scripts/gen-tokens.mjs — DO NOT EDIT.
 *
 *   @import "tailwindcss";
 *   @import "@hanzo/design/tailwind.css";
 *
 * It carries the tokens AND maps them onto Tailwind's utility namespace, so
 * \`bg-background\`, \`text-muted-foreground\` and \`border-border\` resolve to the
 * system's values with nothing to wire up by hand.
 *
 * Import it AFTER tailwindcss: @theme has to come after the framework it
 * extends, and the element defaults are layered so your utilities still win.
 *
 * "inline" is deliberate — it compiles \`border-border\` to var(--border) rather
 * than to that variable's build-time value, so switching .light at runtime moves
 * the UI and not merely the variables.
 *
 * The tokens are inlined below rather than @imported for the reason styles.css
 * is flattened: an @import must precede every other rule, so importing this
 * after tailwindcss would invalidate it and the browser would drop the whole
 * token layer without a word.
 */
${bundle}

@theme inline {
${SLOTS.map((s) => `  --color-${s}: var(--${s});`).join('\n')}

${Object.entries(STATE).map(([k, v]) => `  --color-${k}: var(--${v});`).join('\n')}

  --radius-sm: var(--radius-sm);
  --radius-md: var(--radius-md);
  --radius-lg: var(--radius-lg);
  --radius-xl: var(--radius-xl);

  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);
}
`
writeFileSync(join(root, 'tailwind.css'), tw)
console.log(`gen-tokens: wrote tailwind.css — ${SLOTS.length} colour slots + ${Object.keys(STATE).length} states`)
